# Simple definition to run boman-cli tool
# Make sure you have boman.yaml file in your repo

trigger:
- master

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8' # 3.6,3.7,3.9 
- script: |
    pip install boman-cli --upgrade
    boman-cli -a run -u https://devapi.boman.ai/v2/
  displayName: 'install boman-cli and run scan'